# version: '3.8'
# services:
#   edit:
#     image: whoatemyapplepie/golang:1.22.2-bullseye
#     build:
#       context: edit
#       args:
#         - USERNAME=${USERNAME}
#         - GROUPNAME=${GROUPNAME}
#     volumes:
#       - ../:/home/${USERNAME}/
#     user: "${UID}:${GID}"
#     tty: true

services:
  go_app:
    build:
      context: practice_go_edit
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GROUPNAME=${GROUPNAME}
        - GID=${GID}
    container_name: practice_go_edit
    volumes:
      - ../:/home/${USERNAME}/go/src/app
    tty: true
