services:
  go_app:
    image: whoatemyapplepie/practice-go:1.22.2-bullseye
    build:
      context: practice_go_edit
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GROUPNAME=${GROUPNAME}
        - GID=${GID}
    container_name: practice_go_edit
    volumes:
      - ../:/home/${USERNAME}/go/src/app
    tty: true
